name: Publish

on:
  release:
    types: [ created ]

jobs:
  npm:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout Code
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
        name: Install dependencies
      - run: npm test
        name: Run tests
      - run: npm publish
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}